name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: [linux-x64-spot, self-hosted]
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Ashley"
